[build]
command = "npm run build"
publish = "dist"

[[redirects]]
from = "/api/quotes/random"
to = "https://api.quotable.io/random"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200